CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    username VARCHAR(250) NOT NULL UNIQUE,
    password VARCHAR(250) NOT NULL,
    class_assigend VARCHAR(250) NOT NULL
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);