-- Add new subject columns to exam_results table
ALTER TABLE exam_results 
ADD COLUMN `LS/SP` INT DEFAULT NULL,
ADD COLUMN RDG INT DEFAULT NULL,
ADD COLUMN GRM INT DEFAULT NULL,
ADD COLUMN WRI INT DEFAULT NULL,
ADD COLUMN `KUS/KUZ` INT DEFAULT NULL,
ADD COLUMN KUS INT DEFAULT NULL,
ADD COLUMN LUG INT DEFAULT NULL,
ADD COLUMN KUA INT DEFAULT NULL;

-- Add new subject columns to exam_mean_scores table
ALTER TABLE exam_mean_scores
ADD COLUMN `LS/SP` FLOAT DEFAULT NULL,
ADD COLUMN RDG FLOAT DEFAULT NULL,
ADD COLUMN GRM FLOAT DEFAULT NULL,
ADD COLUMN WRI FLOAT DEFAULT NULL,
ADD COLUMN `KUS/KUZ` FLOAT DEFAULT NULL,
ADD COLUMN KUS FLOAT DEFAULT NULL,
ADD COLUMN LUG FLOAT DEFAULT NULL,
ADD COLUMN KUA FLOAT DEFAULT NULL;
