ALTER TABLE exam_results ADD COLUMN `LS/SP` INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN RDG INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN GRM INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN WRI INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN `KUS/KUZ` INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN KUS INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN LUG INT DEFAULT NULL;
ALTER TABLE exam_results ADD COLUMN KUA INT DEFAULT NULL;

ALTER TABLE exam_mean_scores ADD COLUMN `LS/SP` FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN RDG FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN GRM FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN WRI FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN `KUS/KUZ` FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN KUS FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN LUG FLOAT DEFAULT NULL;
ALTER TABLE exam_mean_scores ADD COLUMN KUA FLOAT DEFAULT NULL;